import { AppContextProvider } from "@/features/auth/context/app-context";
import AppShell from "@/shared/components/app-shell";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import type { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Outfit({ subsets: ["latin"], weight: ["300", "400", "500"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.className}antialiased text-gray-700`}
      >
        <AppContextProvider>
          <Toaster />
          <AppShell>{children}</AppShell>
        </AppContextProvider>
      </body>
    </html>
  );
}
